"""added restaurant fields

Revision ID: 01468978d8d2
Revises: 1fcfbf3b2ae6
Create Date: 2026-05-04 12:03:20.781897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01468978d8d2'
down_revision = '1fcfbf3b2ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_hours', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('floor_plan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('floor_plan')
        batch_op.drop_column('delivery_time')
        batch_op.drop_column('opening_hours')

    # ### end Alembic commands ###
